/**
 * Grand Staff - Two-hand display with brace connector
 * Part of the Phase 4.4 VexFlow Professional Notation enhancement
 *
 * This module handles rendering a grand staff with treble (right hand) and
 * bass (left hand) clefs, connected by a brace and shared barlines.
 */

import {
  createRenderer,
  createStave,
  createStaveNote,
  createChordNote,
  createRest,
  createVoice,
  generateBeams,
  drawBeams,
  getVexFlowKeySignature,
  noteToMidi,
  midiToNote,
  parseNote,
  getOctaveShift,
  applyOctaveShift,
  CLEF_RANGES,
} from './vexFlowRenderer.js';

import { analyzeChordTone, CHORD_TONE_COLORS } from '../analysis/chordToneAnalyzer.js';

// VexFlow is loaded globally
// Use a getter function to check at runtime, not at module load time
// VexFlow 5.x uses window.VexFlow, older versions use window.Vex.Flow
function getVF() {
  return window.VexFlow || (window.Vex ? window.Vex.Flow : null);
}

// ============================================================================
// CONSTANTS
// ============================================================================

/**
 * Default dimensions for grand staff layout
 */
export const GRAND_STAFF_DEFAULTS = {
  measureWidth: 220,           // Width of each measure
  staffSpacing: 80,            // Vertical space between staves
  systemMarginTop: 20,         // Top margin for first system
  systemMarginBottom: 160,     // Bottom margin (increased for chord brackets + deep bass ledger lines)
  braceWidth: 15,              // Width for the brace
  measurePadding: 10,          // Padding within measures
  clefWidth: 30,               // Width for clef
  keySignatureWidth: 20,       // Width per accidental in key signature
  timeSignatureWidth: 30,      // Width for time signature
};

/**
 * Get staff connector types (must be called at runtime when VF is available)
 */
function getConnectorTypes() {
  const VF = getVF();
  return {
    BRACE: VF ? VF.StaveConnector.type.BRACE : 1,
    SINGLE_LEFT: VF ? VF.StaveConnector.type.SINGLE_LEFT : 4,
    SINGLE_RIGHT: VF ? VF.StaveConnector.type.SINGLE_RIGHT : 0,
    BRACKET: VF ? VF.StaveConnector.type.BRACKET : 3,
  };
}

// ============================================================================
// NOTE COLORING
// ============================================================================

/**
 * Apply coloring to VexFlow notes based on harmonic analysis and playback state
 * @param {Array} vexNotes - Array of VexFlow note objects
 * @param {Array} noteData - Original note data with pitch info
 * @param {Object} options - Coloring options
 */
function applyNoteColoring(vexNotes, noteData, options = {}) {
  const {
    measureIndex = 0,
    chord = null,
    keySignature = 'C',
    activeNotes = null,
    enableHarmonicColoring = false,
    isBass = false,
    isAutoGeneratedBass = false,  // Only color bass blue if auto-generated
  } = options;


  // Color constants
  const ACTIVE_COLOR = '#EF4444';         // Red for actively playing
  const BASS_COLOR = '#3B82F6';           // Blue for auto-generated bass notes
  const DEFAULT_COLOR = '#000000';        // Black default

  for (let i = 0; i < vexNotes.length; i++) {
    const vexNote = vexNotes[i];
    const note = noteData[i];

    // Skip rests
    if (!note || note.isRest || vexNote.isRest()) {
      continue;
    }

    // Get pitch(es) for this note
    const pitches = note.pitches || (note.pitch ? [note.pitch] : []);
    if (pitches.length === 0) continue;

    let fillStyle = DEFAULT_COLOR;
    let strokeStyle = DEFAULT_COLOR;

    // Priority 1: Check if any note in this chord is actively playing
    const isActive = activeNotes && pitches.some(pitch => {
      // Note ID format: "measureIndex-beat-pitch"
      const beat = note.beat || 0;
      const noteId = `${measureIndex}-${beat}-${pitch}`;
      const hasNote = activeNotes.has(noteId);
      return hasNote;
    });

    if (isActive) {
      fillStyle = ACTIVE_COLOR;
      strokeStyle = '#DC2626'; // Darker red for stroke
    } else if (isBass && isAutoGeneratedBass) {
      // Only auto-generated bass notes are blue
      // Chord notes remain black
      fillStyle = BASS_COLOR;
      strokeStyle = '#2563EB'; // Darker blue for stroke
    } else if (enableHarmonicColoring && chord && chord.root && !isBass) {
      // Apply harmonic tone coloring - ONLY to treble clef (melody notes)
      // Bass clef notes should remain black
      const primaryPitch = pitches[0];
      try {
        const analysis = analyzeChordTone(primaryPitch, chord, keySignature);
        if (analysis && analysis.colors) {
          fillStyle = analysis.colors.fill;
          strokeStyle = analysis.colors.stroke;
        }
      } catch (e) {
        // Fall back to default if analysis fails
      }
    }

    // Apply the style to the VexFlow note
    try {
      vexNote.setStyle({
        fillStyle: fillStyle,
        strokeStyle: strokeStyle,
      });
    } catch (e) {
      // Some note types may not support setStyle
    }
  }
}

// ============================================================================
// GRAND STAFF DIMENSIONS
// ============================================================================

/**
 * Calculate dimensions for a grand staff system
 * @param {Object} options - Calculation options
 * @returns {Object} - Dimension calculations
 */
export function calculateGrandStaffDimensions(options = {}) {
  const {
    numMeasures = 4,
    measuresPerLine = 4,
    measureWidth = GRAND_STAFF_DEFAULTS.measureWidth,
    staffSpacing = GRAND_STAFF_DEFAULTS.staffSpacing,
    systemMarginTop = GRAND_STAFF_DEFAULTS.systemMarginTop,
    systemMarginBottom = GRAND_STAFF_DEFAULTS.systemMarginBottom,
    braceWidth = GRAND_STAFF_DEFAULTS.braceWidth,
    showClef = true,
    showKeySignature = true,
    showTimeSignature = true,
    keySignature = 'C',
  } = options;

  // Calculate number of rows/systems
  const numSystems = Math.ceil(numMeasures / measuresPerLine);

  // Calculate width for notation elements on first measure of each system
  let firstMeasureExtra = 0;
  if (showClef) firstMeasureExtra += GRAND_STAFF_DEFAULTS.clefWidth;
  if (showKeySignature) {
    const numAccidentals = getKeySignatureAccidentalCount(keySignature);
    firstMeasureExtra += numAccidentals * GRAND_STAFF_DEFAULTS.keySignatureWidth;
  }
  if (showTimeSignature) firstMeasureExtra += GRAND_STAFF_DEFAULTS.timeSignatureWidth;

  // Calculate total width
  const measuresInRow = Math.min(numMeasures, measuresPerLine);
  const contentWidth = braceWidth + firstMeasureExtra + (measuresInRow * measureWidth);
  const totalWidth = contentWidth + 40; // Add padding

  // Calculate height for each system (treble + bass + spacing)
  const staffHeight = 80; // Standard 5-line staff height
  const systemHeight = (staffHeight * 2) + staffSpacing + systemMarginTop + systemMarginBottom;

  // Total height
  const totalHeight = numSystems * systemHeight;

  return {
    numSystems,
    measuresPerLine,
    measureWidth,
    staffSpacing,
    staffHeight,
    systemHeight,
    totalWidth,
    totalHeight,
    braceWidth,
    firstMeasureExtra,
    trebleY: systemMarginTop,
    bassY: systemMarginTop + staffHeight + staffSpacing,
  };
}

/**
 * Get the number of accidentals in a key signature
 * @param {string} key - Key name
 * @returns {number} - Number of accidentals
 */
function getKeySignatureAccidentalCount(key) {
  const sharpKeys = ['G', 'D', 'A', 'E', 'B', 'F#', 'C#'];
  const flatKeys = ['F', 'Bb', 'Eb', 'Ab', 'Db', 'Gb', 'Cb'];

  const normalized = getVexFlowKeySignature(key).replace('m', '');

  let sharpIndex = sharpKeys.indexOf(normalized);
  if (sharpIndex !== -1) return sharpIndex + 1;

  let flatIndex = flatKeys.indexOf(normalized);
  if (flatIndex !== -1) return flatIndex + 1;

  return 0;
}

// ============================================================================
// GRAND STAFF RENDERING
// ============================================================================

/**
 * Render a grand staff measure (treble + bass with brace)
 * @param {Object} context - VexFlow context
 * @param {Object} measureData - Data for both hands
 * @param {Object} options - Rendering options
 * @returns {Object} - { trebleStave, bassStave, connectors }
 */
export function renderGrandStaffMeasure(context, measureData, options = {}) {
  const VF = getVF();
  if (!VF) {
    console.error('VexFlow not loaded');
    return null;
  }

  const CONNECTOR_TYPES = getConnectorTypes();

  const {
    x = 10,
    y = 40,
    width = GRAND_STAFF_DEFAULTS.measureWidth,
    staffSpacing = GRAND_STAFF_DEFAULTS.staffSpacing,
    keySignature = 'C',
    timeSignature = '4/4',
    showClef = true,
    showKeySignature = true,
    showTimeSignature = true,
    showBrace = true,
    showBarlines = true,
    isFirstInSystem = true,
    isLastInSystem = false,
    measureNumber = null,
    // Coloring options
    measureIndex = 0,
    chord = null,           // Chord for harmonic analysis {root, type}
    activeNotes = null,     // Set of active note IDs for red highlighting
    enableHarmonicColoring = false,
    isAutoGeneratedBass = false,  // Only color bass notes blue if auto-generated
  } = options;

  const {
    trebleNotes = [],  // Array of note data for treble clef
    bassNotes = [],    // Array of note data for bass clef
  } = measureData;

  // Calculate bass staff Y position
  const trebleY = y;
  const bassY = y + 80 + staffSpacing; // 80 = staff height

  // Create treble stave
  const trebleStave = createStave({
    x,
    y: trebleY,
    width,
    clef: 'treble',
    keySignature: isFirstInSystem ? keySignature : null,
    timeSignature: isFirstInSystem ? timeSignature : null,
    showClef: isFirstInSystem && showClef,
    showKeySignature: isFirstInSystem && showKeySignature,
    showTimeSignature: isFirstInSystem && showTimeSignature,
  });

  // Create bass stave
  const bassStave = createStave({
    x,
    y: bassY,
    width,
    clef: 'bass',
    keySignature: isFirstInSystem ? keySignature : null,
    timeSignature: isFirstInSystem ? timeSignature : null,
    showClef: isFirstInSystem && showClef,
    showKeySignature: isFirstInSystem && showKeySignature,
    showTimeSignature: isFirstInSystem && showTimeSignature,
  });

  // Set barlines
  if (showBarlines) {
    if (isLastInSystem) {
      trebleStave.setEndBarType(VF.Barline.type.END);
      bassStave.setEndBarType(VF.Barline.type.END);
    } else {
      trebleStave.setEndBarType(VF.Barline.type.SINGLE);
      bassStave.setEndBarType(VF.Barline.type.SINGLE);
    }
  }

  // Add measure number
  if (measureNumber !== null && isFirstInSystem) {
    trebleStave.setMeasure(measureNumber);
  }

  // Draw staves
  trebleStave.setContext(context).draw();
  bassStave.setContext(context).draw();

  // Create connectors
  const connectors = [];

  if (showBrace && isFirstInSystem) {
    // Brace on the left
    const brace = new VF.StaveConnector(trebleStave, bassStave);
    brace.setType(CONNECTOR_TYPES.BRACE);
    brace.setContext(context).draw();
    connectors.push(brace);

    // Left line
    const leftLine = new VF.StaveConnector(trebleStave, bassStave);
    leftLine.setType(CONNECTOR_TYPES.SINGLE_LEFT);
    leftLine.setContext(context).draw();
    connectors.push(leftLine);
  }

  // Right barline connector
  if (showBarlines) {
    const rightLine = new VF.StaveConnector(trebleStave, bassStave);
    rightLine.setType(CONNECTOR_TYPES.SINGLE_RIGHT);
    rightLine.setContext(context).draw();
    connectors.push(rightLine);
  }

  // Render treble notes
  const trebleResult = createNotesForStaff(trebleNotes, keySignature, 'treble', timeSignature);
  const vexTrebleNotes = trebleResult.notes;
  const trebleOttavaBrackets = trebleResult.ottavaBrackets;
  const trebleTies = trebleResult.ties;
  const trebleBeams = generateBeams(vexTrebleNotes.filter(n => !n.isRest()));

  // Render bass notes
  const bassResult = createNotesForStaff(bassNotes, keySignature, 'bass', timeSignature);
  const vexBassNotes = bassResult.notes;
  const bassOttavaBrackets = bassResult.ottavaBrackets;
  const bassTies = bassResult.ties;
  const bassBeams = generateBeams(vexBassNotes.filter(n => !n.isRest()));

  // Apply note coloring
  applyNoteColoring(vexTrebleNotes, trebleNotes, {
    measureIndex,
    chord,
    keySignature,
    activeNotes,
    enableHarmonicColoring,
    clef: 'treble',
  });

  applyNoteColoring(vexBassNotes, bassNotes, {
    measureIndex,
    chord,
    keySignature,
    activeNotes,
    enableHarmonicColoring,
    clef: 'bass',
    isBass: true,
    isAutoGeneratedBass,  // Only color blue if auto-generated
  });

  // Create voices
  const [num, denom] = timeSignature.split('/');
  const voiceOptions = {
    numBeats: parseInt(num, 10),
    beatValue: parseInt(denom, 10),
  };

  const trebleVoice = createVoice(vexTrebleNotes, voiceOptions);
  const bassVoice = createVoice(vexBassNotes, voiceOptions);

  // Format and draw voices
  if (vexTrebleNotes.length > 0 && vexBassNotes.length > 0) {
    const formatter = new VF.Formatter();
    formatter.joinVoices([trebleVoice]);
    formatter.joinVoices([bassVoice]);

    const staveWidth = width - trebleStave.getNoteStartX() + x;
    formatter.format([trebleVoice, bassVoice], staveWidth);

    trebleVoice.draw(context, trebleStave);
    bassVoice.draw(context, bassStave);
  }

  // Draw beams
  drawBeams(context, trebleBeams);
  drawBeams(context, bassBeams);

  // Draw ties (only within same measure for now)
  // TODO: Cross-measure ties need to be handled at the system level
  trebleTies.forEach(tieInfo => {
    if (tieInfo.startIndex < vexTrebleNotes.length - 1) {
      const staveTie = new VF.StaveTie({
        first_note: vexTrebleNotes[tieInfo.startIndex],
        last_note: vexTrebleNotes[tieInfo.startIndex + 1],
        first_indices: [0],
        last_indices: [0]
      });
      staveTie.setContext(context).draw();
    }
  });

  bassTies.forEach(tieInfo => {
    if (tieInfo.startIndex < vexBassNotes.length - 1) {
      const staveTie = new VF.StaveTie({
        first_note: vexBassNotes[tieInfo.startIndex],
        last_note: vexBassNotes[tieInfo.startIndex + 1],
        first_indices: [0],
        last_indices: [0]
      });
      staveTie.setContext(context).draw();
    }
  });

  // Collect note regions for tooltip detection
  // Bounding boxes are available after draw()
  const noteRegions = [];

  // Collect treble note regions
  vexTrebleNotes.forEach((vexNote, noteIdx) => {
    try {
      const boundingBox = vexNote.getBoundingBox();
      if (boundingBox && trebleNotes[noteIdx]) {
        const noteData = trebleNotes[noteIdx];
        noteRegions.push({
          staff: 'treble',
          measureIndex,
          noteIndex: noteIdx,
          pitch: noteData.pitch || (noteData.pitches ? noteData.pitches[0] : null),
          pitches: noteData.pitches || (noteData.pitch ? [noteData.pitch] : []),
          beat: noteData.beat || noteIdx,
          duration: noteData.duration || '4n',
          dotted: noteData.dotted || false,  // Include dotted for beat calculations
          isRest: noteData.isRest || false,
          bounds: {
            x: boundingBox.getX() - 10,
            y: boundingBox.getY() - 10,
            width: boundingBox.getW() + 20,
            height: boundingBox.getH() + 20,
          },
        });
      }
    } catch (e) {
      // Ignore bounding box errors
    }
  });

  // Collect bass note regions
  vexBassNotes.forEach((vexNote, noteIdx) => {
    try {
      const boundingBox = vexNote.getBoundingBox();
      if (boundingBox && bassNotes[noteIdx]) {
        const noteData = bassNotes[noteIdx];
        noteRegions.push({
          staff: 'bass',
          measureIndex,
          noteIndex: noteIdx,
          pitch: noteData.pitch || (noteData.pitches ? noteData.pitches[0] : null),
          pitches: noteData.pitches || (noteData.pitch ? [noteData.pitch] : []),
          beat: noteData.beat || noteIdx,
          duration: noteData.duration || '4n',
          dotted: noteData.dotted || false,  // Include dotted for beat calculations
          isRest: noteData.isRest || false,
          bounds: {
            x: boundingBox.getX() - 10,
            y: boundingBox.getY() - 10,
            width: boundingBox.getW() + 20,
            height: boundingBox.getH() + 20,
          },
        });
      }
    } catch (e) {
      // Ignore bounding box errors
    }
  });

  // Draw chord symbol if present in measure data
  if (measureData.metadata && measureData.metadata.chordSymbol) {
    const chordSymbol = measureData.metadata.chordSymbol;
    // Position at beginning of measure (with small left padding)
    const chordX = x + 5;
    // Position 30px above treble staff, but never go below y=15 to stay on canvas
    const chordY = Math.max(15, trebleY - 30);

    // Use VexFlow's CanvasContext methods for text rendering
    // Standard notation style: black, serif font, moderate size
    const VF = getVF();
    if (VF && context) {
      context.save();
      context.setFont('Times New Roman, serif', 14, 'normal');
      context.setFillStyle('#000000'); // Black (standard for chord symbols)
      context.fillText(chordSymbol, chordX, chordY);
      context.restore();
    }
  }

  return {
    trebleStave,
    bassStave,
    connectors,
    trebleVoice,
    bassVoice,
    trebleNotes: vexTrebleNotes,
    bassNotes: vexBassNotes,
    trebleOttavaBrackets,
    bassOttavaBrackets,
    noteRegions,
  };
}

/**
 * Apply ottava adjustment to notes for comfortable display in clef
 * Notes too high get 8va (shift down for display), notes too low get 8vb (shift up for display)
 * @param {Array} pitches - Array of pitch strings
 * @param {string} clef - 'treble' or 'bass'
 * @returns {Object} - { adjustedPitches, ottavaLabel, ottavaShift }
 */
function applyOttavaAdjustment(pitches, clef) {
  if (!pitches || pitches.length === 0) {
    return { adjustedPitches: pitches, ottavaLabel: null, ottavaShift: 0 };
  }

  const range = CLEF_RANGES[clef];

  // Check if any notes need adjustment
  let needsShiftDown = false;  // 8va - notes too high
  let needsShiftUp = false;    // 8vb - notes too low

  for (const pitch of pitches) {
    const midi = noteToMidi(pitch);
    if (midi > range.max) {
      needsShiftDown = true;
    } else if (midi < range.min) {
      needsShiftUp = true;
    }
  }

  // If conflicting needs, prioritize based on average pitch
  if (needsShiftDown && needsShiftUp) {
    const avgMidi = pitches.reduce((sum, p) => sum + noteToMidi(p), 0) / pitches.length;
    const midRange = (range.min + range.max) / 2;
    if (avgMidi > midRange) {
      needsShiftUp = false;  // More notes are high
    } else {
      needsShiftDown = false;  // More notes are low
    }
  }

  if (needsShiftDown) {
    // Shift all notes down one octave for display, mark with 8va
    const adjustedPitches = pitches.map(pitch => applyOctaveShift(pitch, -1));
    return { adjustedPitches, ottavaLabel: '8va', ottavaShift: -1 };
  } else if (needsShiftUp) {
    // Shift all notes up one octave for display, mark with 8vb
    const adjustedPitches = pitches.map(pitch => applyOctaveShift(pitch, 1));
    return { adjustedPitches, ottavaLabel: '8vb', ottavaShift: 1 };
  }

  return { adjustedPitches: pitches, ottavaLabel: null, ottavaShift: 0 };
}

/**
 * Create VexFlow notes for a staff from note data
 * @param {Array} notes - Array of note data
 * @param {string} keySignature - Key signature
 * @param {string} clef - Clef type
 * @param {string} timeSignature - Time signature
 * @returns {Object} - { notes: Array of VexFlow StaveNotes, ottavaBrackets: Array of bracket info }
 */
function createNotesForStaff(notes, keySignature, clef, timeSignature) {
  const VF = getVF();

  if (!notes || notes.length === 0) {
    // Return a whole rest for empty measures
    return { notes: [createRest('1n', clef)], ottavaBrackets: [], ties: [] };
  }

  const vexNotes = [];
  const ottavaBrackets = []; // Track brackets: { startIndex, endIndex, label }
  const ties = []; // Track tie starts for rendering
  let currentBracket = null;

  for (let i = 0; i < notes.length; i++) {
    const note = notes[i];

    if (note.isRest) {
      // Rests end any current bracket
      if (currentBracket) {
        currentBracket.endIndex = vexNotes.length - 1;
        if (currentBracket.endIndex >= currentBracket.startIndex) {
          ottavaBrackets.push(currentBracket);
        }
        currentBracket = null;
      }
      vexNotes.push(createRest(note.duration || '4n', clef));
    } else if (note.pitches && Array.isArray(note.pitches)) {
      // Chord - apply ottava adjustment
      const { adjustedPitches, ottavaLabel } = applyOttavaAdjustment(note.pitches, clef);
      const chordNote = createChordNote(adjustedPitches, note.duration || '4n', keySignature, clef, note.dotted || false, note.articulation || null, note.accidental || null);

      // Preserve isTied property for cross-measure tie rendering
      console.log('[createBassVoice] Processing note:', {
        noteIsTied: note.isTied,
        noteHasIsTied: 'isTied' in note,
        noteKeys: Object.keys(note),
        beat: note.beat
      });
      if (note.isTied !== undefined) {
        chordNote.isTied = note.isTied;
        console.log('[createBassVoice] Attached isTied to VexFlow note:', chordNote.isTied);
      }

      // Track ottava brackets
      if (ottavaLabel) {
        if (currentBracket && currentBracket.label === ottavaLabel) {
          // Continue existing bracket
          currentBracket.endIndex = vexNotes.length;
        } else {
          // End previous bracket if different label
          if (currentBracket) {
            if (currentBracket.endIndex >= currentBracket.startIndex) {
              ottavaBrackets.push(currentBracket);
            }
          }
          // Start new bracket
          currentBracket = {
            startIndex: vexNotes.length,
            endIndex: vexNotes.length,
            label: ottavaLabel,
          };
        }
      } else if (currentBracket) {
        // No ottava needed, end current bracket
        if (currentBracket.endIndex >= currentBracket.startIndex) {
          ottavaBrackets.push(currentBracket);
        }
        currentBracket = null;
      }

      vexNotes.push(chordNote);
    } else if (note.pitch) {
      // Single note - apply ottava adjustment
      const { adjustedPitches, ottavaLabel } = applyOttavaAdjustment([note.pitch], clef);
      const adjustedNote = { ...note, pitch: adjustedPitches[0] };
      const staveNote = createStaveNote(adjustedNote, keySignature, clef);

      // Preserve isTied property for cross-measure tie rendering
      if (note.isTied !== undefined) {
        staveNote.isTied = note.isTied;
      }

      // Track ottava brackets
      if (ottavaLabel) {
        if (currentBracket && currentBracket.label === ottavaLabel) {
          // Continue existing bracket
          currentBracket.endIndex = vexNotes.length;
        } else {
          // End previous bracket if different label
          if (currentBracket) {
            if (currentBracket.endIndex >= currentBracket.startIndex) {
              ottavaBrackets.push(currentBracket);
            }
          }
          // Start new bracket
          currentBracket = {
            startIndex: vexNotes.length,
            endIndex: vexNotes.length,
            label: ottavaLabel,
          };
        }
      } else if (currentBracket) {
        // No ottava needed, end current bracket
        if (currentBracket.endIndex >= currentBracket.startIndex) {
          ottavaBrackets.push(currentBracket);
        }
        currentBracket = null;
      }

      vexNotes.push(staveNote);
    }

    // Track ties: if this note has tied=true, mark it for tie rendering
    if (note.tied && vexNotes.length > 0) {
      ties.push({
        startIndex: vexNotes.length - 1,
        // We'll find the end note in the next measure or later in this function
      });
    }
  }

  // Close any remaining bracket
  if (currentBracket && currentBracket.endIndex >= currentBracket.startIndex) {
    ottavaBrackets.push(currentBracket);
  }

  return { notes: vexNotes, ottavaBrackets, ties };
}

// ============================================================================
// FULL SYSTEM RENDERING
// ============================================================================

/**
 * Render a complete grand staff system (multiple measures)
 * @param {Object} container - Canvas or div container
 * @param {Array} measures - Array of measure data
 * @param {Object} options - Rendering options
 * @returns {Object} - Rendered system information
 */
export function renderGrandStaffSystem(container, measures, options = {}) {
  const VF = getVF();
  if (!VF || !measures) {
    console.error('[renderGrandStaffSystem] VexFlow not loaded or no measures provided');
    return null;
  }

  const {
    measuresPerLine = 4,
    measureWidth = GRAND_STAFF_DEFAULTS.measureWidth,
    staffSpacing = GRAND_STAFF_DEFAULTS.staffSpacing,
    keySignature = 'C',
    timeSignature = '4/4',
    startMeasureNumber = 1,
    showMeasureNumbers = true,
    // Highlighting options
    selectedMeasureIndex = -1,   // Blue border for selected measure
    activeMeasureIndex = -1,     // Yellow background for playing measure
    activeNotes = null,          // Set of note IDs for red highlighting
    enableHarmonicColoring = false, // Enable chord tone coloring
    showChordSpans = true,       // Show chord span shading and brackets
  } = options;

  // Calculate dimensions
  const dimensions = calculateGrandStaffDimensions({
    numMeasures: measures.length,
    measuresPerLine,
    measureWidth,
    staffSpacing,
    keySignature,
    ...options,
  });

  // Create renderer
  const { renderer, context } = createRenderer(
    container,
    dimensions.totalWidth,
    dimensions.totalHeight
  );

  if (!context) return null;

  // Get the SVG or canvas context for direct drawing
  const svgContext = context.svg || context;

  // Helper function to draw measure highlights
  function drawMeasureHighlight(measureIndex, color, isBorder = false) {
    const systemIndex = Math.floor(measureIndex / measuresPerLine);
    const measureInSystem = measureIndex % measuresPerLine;
    const isFirstInSystem = measureInSystem === 0;

    const x = dimensions.braceWidth + (measureInSystem * measureWidth) +
      (isFirstInSystem ? 0 : dimensions.firstMeasureExtra);
    const y = dimensions.trebleY + (systemIndex * dimensions.systemHeight);
    const w = isFirstInSystem
      ? measureWidth + dimensions.firstMeasureExtra
      : measureWidth;
    const h = dimensions.systemHeight - GRAND_STAFF_DEFAULTS.systemMarginTop - GRAND_STAFF_DEFAULTS.systemMarginBottom;

    // Draw using VexFlow's SVG context
    if (context.svg) {
      // SVG renderer
      const rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
      rect.setAttribute('x', x);
      rect.setAttribute('y', y);
      rect.setAttribute('width', w);
      rect.setAttribute('height', h);

      if (isBorder) {
        rect.setAttribute('fill', 'none');
        rect.setAttribute('stroke', color);
        rect.setAttribute('stroke-width', '2');
      } else {
        rect.setAttribute('fill', color);
        rect.setAttribute('stroke', 'none');
      }

      // Insert at beginning so it's behind other elements
      context.svg.insertBefore(rect, context.svg.firstChild);
    } else if (context.context2D || context.vexFlowCanvasContext) {
      // Canvas renderer
      const ctx = context.context2D || context.vexFlowCanvasContext;
      if (ctx) {
        ctx.save();
        if (isBorder) {
          ctx.strokeStyle = color;
          ctx.lineWidth = 2;
          ctx.strokeRect(x, y, w, h);
        } else {
          ctx.fillStyle = color;
          ctx.fillRect(x, y, w, h);
        }
        ctx.restore();
      }
    }
  }

  // Draw partial measure highlight for chord spans that don't align with measure boundaries
  // startBeat and endBeat are absolute beat positions from the beginning of the piece
  function drawChordSpanHighlight(startBeat, endBeat, color) {
    const beatsPerMeasure = timeSignature.num || timeSignature.numerator || 4;

    // Convert absolute beats to measure + beat positions
    const startMeasure = Math.floor(startBeat / beatsPerMeasure);
    const startBeatInMeasure = startBeat % beatsPerMeasure;
    const endMeasure = Math.floor(endBeat / beatsPerMeasure);
    const endBeatInMeasure = endBeat % beatsPerMeasure;

    // Draw the span across measures
    for (let m = startMeasure; m <= endMeasure; m++) {
      if (m >= measures.length) break;

      const systemIndex = Math.floor(m / measuresPerLine);
      const measureInSystem = m % measuresPerLine;
      const isFirstInSystem = measureInSystem === 0;

      const measureX = dimensions.braceWidth + (measureInSystem * measureWidth) +
        (isFirstInSystem ? 0 : dimensions.firstMeasureExtra);
      const y = dimensions.trebleY + (systemIndex * dimensions.systemHeight);
      const fullWidth = isFirstInSystem
        ? measureWidth + dimensions.firstMeasureExtra
        : measureWidth;
      const h = dimensions.systemHeight - GRAND_STAFF_DEFAULTS.systemMarginTop - GRAND_STAFF_DEFAULTS.systemMarginBottom;

      // Calculate horizontal position and width within this measure
      let x, w;

      if (m === startMeasure && m === endMeasure) {
        // Chord starts and ends in same measure
        const startFraction = startBeatInMeasure / beatsPerMeasure;
        const endFraction = endBeatInMeasure / beatsPerMeasure;
        x = measureX + (fullWidth * startFraction);
        w = fullWidth * (endFraction - startFraction);
      } else if (m === startMeasure) {
        // First measure of span - from startBeat to end of measure
        const startFraction = startBeatInMeasure / beatsPerMeasure;
        x = measureX + (fullWidth * startFraction);
        w = fullWidth * (1 - startFraction);
      } else if (m === endMeasure) {
        // Last measure of span - from start of measure to endBeat
        // If endBeatInMeasure is 0, it means the chord ends exactly at the start of this measure,
        // so we shouldn't draw anything in this measure (the previous measure was the last)
        const endFraction = endBeatInMeasure === 0 ? 0 : endBeatInMeasure / beatsPerMeasure;
        // For first measure in system, beats start after the clef/key/time signature
        // So we need to offset x and adjust the width calculation
        if (isFirstInSystem) {
          x = measureX + dimensions.firstMeasureExtra;
          w = measureWidth * endFraction;
        } else {
          x = measureX;
          w = fullWidth * endFraction;
        }
      } else {
        // Middle measure - full width
        x = measureX;
        w = fullWidth;
      }

      // Draw the highlight
      if (context.svg) {
        const rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
        rect.setAttribute('x', x);
        rect.setAttribute('y', y);
        rect.setAttribute('width', w);
        rect.setAttribute('height', h);
        rect.setAttribute('fill', color);
        rect.setAttribute('stroke', 'none');
        context.svg.insertBefore(rect, context.svg.firstChild);
      } else if (context.context2D || context.vexFlowCanvasContext) {
        const ctx = context.context2D || context.vexFlowCanvasContext;
        if (ctx) {
          ctx.save();
          ctx.fillStyle = color;
          ctx.fillRect(x, y, w, h);
          ctx.restore();
        }
      }
    }
  }

  // Draw chord bracket beneath bass clef with chord name
  // Returns the total width of the bracket span across all systems
  function drawChordBracket(startBeat, endBeat, chordName, color) {
    const beatsPerMeasure = timeSignature.num || timeSignature.numerator || 4;
    const startMeasure = Math.floor(startBeat / beatsPerMeasure);
    const startBeatInMeasure = startBeat % beatsPerMeasure;
    const endMeasure = Math.floor(endBeat / beatsPerMeasure);
    const endBeatInMeasure = endBeat % beatsPerMeasure;

    // Group consecutive measures by system
    const systemSpans = [];
    let currentSystem = -1;
    let currentSpan = null;

    for (let m = startMeasure; m <= endMeasure; m++) {
      if (m >= measures.length) break;

      const systemIndex = Math.floor(m / measuresPerLine);
      const measureInSystem = m % measuresPerLine;
      const isFirstInSystem = measureInSystem === 0;

      const measureX = dimensions.braceWidth + (measureInSystem * measureWidth) +
        (isFirstInSystem ? 0 : dimensions.firstMeasureExtra);
      const fullWidth = isFirstInSystem
        ? measureWidth + dimensions.firstMeasureExtra
        : measureWidth;

      // Calculate x position and width for this measure segment
      let segmentX, segmentW;

      if (m === startMeasure && m === endMeasure) {
        const startFraction = startBeatInMeasure / beatsPerMeasure;
        const endFraction = endBeatInMeasure / beatsPerMeasure;
        segmentX = measureX + (fullWidth * startFraction);
        segmentW = fullWidth * (endFraction - startFraction);
      } else if (m === startMeasure) {
        const startFraction = startBeatInMeasure / beatsPerMeasure;
        segmentX = measureX + (fullWidth * startFraction);
        segmentW = fullWidth * (1 - startFraction);
      } else if (m === endMeasure) {
        // If endBeatInMeasure is 0, chord ends exactly at start of this measure
        const endFraction = endBeatInMeasure === 0 ? 0 : endBeatInMeasure / beatsPerMeasure;
        // For first measure in system, beats start after the clef/key/time signature
        if (isFirstInSystem) {
          segmentX = measureX + dimensions.firstMeasureExtra;
          segmentW = measureWidth * endFraction;
        } else {
          segmentX = measureX;
          segmentW = fullWidth * endFraction;
        }
      } else {
        segmentX = measureX;
        segmentW = fullWidth;
      }

      // Start new span if we're on a new system
      if (systemIndex !== currentSystem) {
        if (currentSpan) {
          systemSpans.push(currentSpan);
        }
        currentSystem = systemIndex;
        currentSpan = {
          systemIndex,
          startX: segmentX,
          endX: segmentX + segmentW,
          width: segmentW
        };
      } else {
        // Extend current span
        currentSpan.endX = segmentX + segmentW;
        currentSpan.width = currentSpan.endX - currentSpan.startX;
      }
    }

    // Add final span
    if (currentSpan) {
      systemSpans.push(currentSpan);
    }

    // Draw bracket for each system span
    systemSpans.forEach((span, index) => {
      const bassY = dimensions.trebleY + (span.systemIndex * dimensions.systemHeight) +
                    80 + staffSpacing; // Position of bass staff
      const bracketY = bassY + 120; // Well below the bass staff to accommodate low notes
      const bracketHeight = 15;

      const ctx = context.context2D || context.vexFlowCanvasContext;

      if (context.svg) {
        // SVG rendering
        const group = document.createElementNS('http://www.w3.org/2000/svg', 'g');

        // Horizontal line
        const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        line.setAttribute('x1', span.startX);
        line.setAttribute('y1', bracketY);
        line.setAttribute('x2', span.endX);
        line.setAttribute('y2', bracketY);
        line.setAttribute('stroke', color);
        line.setAttribute('stroke-width', '2');
        group.appendChild(line);

        // Left vertical tick
        const leftTick = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        leftTick.setAttribute('x1', span.startX);
        leftTick.setAttribute('y1', bracketY - bracketHeight / 2);
        leftTick.setAttribute('x2', span.startX);
        leftTick.setAttribute('y2', bracketY + bracketHeight / 2);
        leftTick.setAttribute('stroke', color);
        leftTick.setAttribute('stroke-width', '2');
        group.appendChild(leftTick);

        // Right vertical tick
        const rightTick = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        rightTick.setAttribute('x1', span.endX);
        rightTick.setAttribute('y1', bracketY - bracketHeight / 2);
        rightTick.setAttribute('x2', span.endX);
        rightTick.setAttribute('y2', bracketY + bracketHeight / 2);
        rightTick.setAttribute('stroke', color);
        rightTick.setAttribute('stroke-width', '2');
        group.appendChild(rightTick);

        // Chord name text (only on the first span or if it's the only span)
        if (index === 0) {
          const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
          text.setAttribute('x', span.startX + (span.width / 2));
          text.setAttribute('y', bracketY + 25);
          text.setAttribute('text-anchor', 'middle');
          text.setAttribute('font-family', 'Arial, sans-serif');
          text.setAttribute('font-size', '13');
          text.setAttribute('font-weight', 'bold');
          text.setAttribute('fill', '#333');
          text.textContent = chordName;
          group.appendChild(text);
        }

        context.svg.appendChild(group);
      } else if (ctx) {
        // Canvas rendering
        ctx.save();
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;

        // Horizontal line
        ctx.beginPath();
        ctx.moveTo(span.startX, bracketY);
        ctx.lineTo(span.endX, bracketY);
        ctx.stroke();

        // Left vertical tick
        ctx.beginPath();
        ctx.moveTo(span.startX, bracketY - bracketHeight / 2);
        ctx.lineTo(span.startX, bracketY + bracketHeight / 2);
        ctx.stroke();

        // Right vertical tick
        ctx.beginPath();
        ctx.moveTo(span.endX, bracketY - bracketHeight / 2);
        ctx.lineTo(span.endX, bracketY + bracketHeight / 2);
        ctx.stroke();

        // Chord name text (only on the first span or if it's the only span)
        if (index === 0) {
          ctx.font = 'bold 13px Arial, sans-serif';
          ctx.fillStyle = '#333';
          ctx.textAlign = 'center';
          ctx.textBaseline = 'top';
          ctx.fillText(chordName, span.startX + (span.width / 2), bracketY + 5);
        }

        ctx.restore();
      }
    });
  }

  // Draw measure highlights before rendering measures
  // Active measure (yellow background for playback) - draw first so it's behind
  if (activeMeasureIndex >= 0 && activeMeasureIndex < measures.length) {
    drawMeasureHighlight(activeMeasureIndex, 'rgba(255, 200, 0, 0.25)', false);
  }

  // Selected measure (blue border) - always show, even during playback
  // This helps users see which measure is selected independently of playback state
  if (selectedMeasureIndex >= 0 && selectedMeasureIndex < measures.length) {
    drawMeasureHighlight(selectedMeasureIndex, 'rgba(59, 130, 246, 0.8)', true);
  }

  // Draw chord span shading and brackets - alternating colors for consecutive chords
  // Uses beat-based positioning to show exact horizontal spans, even within measures
  if (showChordSpans) {
    const chordSpanColors = [
      'rgba(200, 220, 255, 0.15)',  // Light blue
      'rgba(220, 255, 220, 0.15)',  // Light green
      'rgba(255, 240, 200, 0.15)',  // Light yellow
      'rgba(255, 220, 220, 0.15)',  // Light red
      'rgba(240, 220, 255, 0.15)',  // Light purple
    ];

    const chordBracketColors = [
      '#4080E0',  // Blue
      '#40B060',  // Green
      '#D0A040',  // Yellow/Gold
      '#D06060',  // Red
      '#9060C0',  // Purple
    ];

    // Get chord information from compositionState to calculate beat positions
    if (window.getCompositionState) {
      const compositionState = window.getCompositionState();
      const chords = compositionState.getChords();

      if (chords && chords.length > 0) {
        let beatOffset = 0;
        chords.forEach((chord, index) => {
          const chordBeats = chord.beats !== undefined ? chord.beats : 4;
          const startBeat = beatOffset;
          const endBeat = beatOffset + chordBeats;

          // Draw the background shading for this chord
          drawChordSpanHighlight(
            startBeat,
            endBeat,
            chordSpanColors[index % chordSpanColors.length]
          );

          // Draw the bracket with chord name beneath bass clef
          // Format chord name with inversion
          let chordName = chord.name || chord.simpleName || `${chord.root}${chord.type || ''}`;

          // Add inversion indicator
          const inversion = chord.inversion || 0;
          if (inversion === 1) {
            chordName += ' (1st)';
          } else if (inversion === 2) {
            chordName += ' (2nd)';
          } else if (inversion === 3) {
            chordName += ' (3rd)';
          }

          drawChordBracket(
            startBeat,
            endBeat,
            chordName,
            chordBracketColors[index % chordBracketColors.length]
          );

          beatOffset += chordBeats;
        });
      }
    }
  }

  // Render each measure
  const renderedMeasures = [];

  for (let i = 0; i < measures.length; i++) {
    const systemIndex = Math.floor(i / measuresPerLine);
    const measureInSystem = i % measuresPerLine;
    const isFirstInSystem = measureInSystem === 0;
    const isLastInSystem = measureInSystem === measuresPerLine - 1 || i === measures.length - 1;

    // Calculate position
    const x = dimensions.braceWidth + (measureInSystem * measureWidth) +
      (isFirstInSystem ? 0 : dimensions.firstMeasureExtra);
    const y = dimensions.trebleY + (systemIndex * dimensions.systemHeight);
    const width = isFirstInSystem
      ? measureWidth + dimensions.firstMeasureExtra
      : measureWidth;

    // Get chord info from measure data for harmonic coloring
    const measureChord = measures[i].chord || null;
    const isAutoGeneratedBass = measures[i].isAutoGeneratedBass || false;

    // Render the measure
    const result = renderGrandStaffMeasure(context, measures[i], {
      x,
      y,
      width,
      staffSpacing,
      keySignature,
      timeSignature,
      isFirstInSystem,
      isLastInSystem,
      measureNumber: showMeasureNumbers ? startMeasureNumber + i : null,
      // Coloring options
      measureIndex: i,
      chord: measureChord,
      activeNotes,
      enableHarmonicColoring,
      isAutoGeneratedBass,
    });

    if (result) {
      // CRITICAL: Get ACTUAL positions from VexFlow staves (not calculated positions)
      // VexFlow may render at different Y positions than we calculated
      const actualTrebleY = result.trebleStave ? result.trebleStave.getY() : y;
      const actualBassY = result.bassStave ? result.bassStave.getY() : y + 80 + staffSpacing;
      const actualX = result.trebleStave ? result.trebleStave.getX() : x;
      const actualWidth = result.trebleStave ? result.trebleStave.getWidth() : width;

      renderedMeasures.push({
        index: i,
        ...result,
        bounds: {
          x,
          y,
          width,
          height: dimensions.systemHeight - dimensions.systemMarginTop - dimensions.systemMarginBottom,
        },
        // ACTUAL positions from VexFlow - use these instead of calculated!
        actualBounds: {
          x: actualX,
          trebleY: actualTrebleY,
          bassY: actualBassY,
          width: actualWidth,
          // System height is from treble top to bass bottom + some margin
          height: (actualBassY - actualTrebleY) + 100, // 100 = staff height + margin
        },
      });
    }
  }

  // Draw cross-measure ottava brackets
  // Track consecutive measures that need the same ottava adjustment
  if (VF && renderedMeasures.length > 0) {
    const TOP_POSITION = VF.TextBracket.Position?.TOP ?? VF.TextBracket.Positions?.TOP ?? 1;
    const BOTTOM_POSITION = VF.TextBracket.Position?.BOTTOM ?? VF.TextBracket.Positions?.BOTTOM ?? -1;

    // Helper to get line position for highest note in a chord
    // For bass clef 8va notes: VexFlow reports them with large positive line numbers
    // We want the SMALLEST line number (most negative or closest to 0) for notes near/above staff
    // But for notes far above bass clef, VexFlow uses large positive numbers, so we also track max
    function getNoteLinePosition(note) {
      try {
        const keyProps = note.getKeyProps();
        if (keyProps && keyProps.length > 0) {
          // Find the smallest line number (typically highest on staff)
          let minLine = Infinity;
          for (const prop of keyProps) {
            if (prop.line < minLine) {
              minLine = prop.line;
            }
          }
          return minLine;
        }
      } catch (e) {
        // Error getting line position
      }
      return 2; // Default to middle of staff
    }

    // Helper to get the highest pitched note's line (largest line number for 8va bass notes)
    function getHighestPitchLine(note) {
      try {
        const keyProps = note.getKeyProps();
        if (keyProps && keyProps.length > 0) {
          // For bass clef 8va notes, highest pitch = largest line number
          let maxLine = -Infinity;
          for (const prop of keyProps) {
            if (prop.line > maxLine) {
              maxLine = prop.line;
            }
          }
          return maxLine;
        }
      } catch (e) {
        // Fallback
      }
      return 2;
    }

    // Helper to get the lowest pitched note's line (smallest line number for 8vb bass notes)
    function getLowestPitchLine(note) {
      try {
        const keyProps = note.getKeyProps();
        if (keyProps && keyProps.length > 0) {
          // For bass clef 8vb notes, lowest pitch = smallest line number
          let minLine = Infinity;
          for (const prop of keyProps) {
            if (prop.line < minLine) {
              minLine = prop.line;
            }
          }
          return minLine;
        }
      } catch (e) {
        // Fallback
      }
      return 2;
    }

    // Process bass clef brackets (where chord progressions are)
    let currentBassOttava = null;
    let bassOttavaStart = null;
    let bassOttavaEnd = null;
    let bassHighestPitchLine = -Infinity; // Track highest pitched note (largest line number for 8va)
    let bassLowestPitchLine = Infinity; // Track lowest pitched note (smallest line number for 8vb)

    for (let i = 0; i < renderedMeasures.length; i++) {
      const measure = renderedMeasures[i];
      const bassNotes = measure.bassNotes;
      const brackets = measure.bassOttavaBrackets;

      // Check if this measure has ottava (for chord progressions, typically one chord per measure)
      const hasOttava = brackets && brackets.length > 0;
      const ottavaLabel = hasOttava ? brackets[0].label : null;

      if (ottavaLabel) {
        if (currentBassOttava === ottavaLabel) {
          // Continue the bracket
          bassOttavaEnd = { measure: i, noteIndex: 0, note: bassNotes[0] };
          // Update extreme note positions
          // For 8va in bass clef, highest pitch has largest line number
          // For 8vb in bass clef, lowest pitch has smallest line number
          const highPitchLine = getHighestPitchLine(bassNotes[0]);
          const lowPitchLine = getLowestPitchLine(bassNotes[0]);
          if (highPitchLine > bassHighestPitchLine) bassHighestPitchLine = highPitchLine;
          if (lowPitchLine < bassLowestPitchLine) bassLowestPitchLine = lowPitchLine;
        } else {
          // Draw previous bracket if exists
          if (currentBassOttava && bassOttavaStart && bassOttavaEnd) {
            try {
              const is8va = currentBassOttava === '8va';
              // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
              const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
              const textBracket = new VF.TextBracket({
                start: bassOttavaStart.note,
                stop: bassOttavaEnd.note,
                text: currentBassOttava,
                superscript: '',
                position: position,
              });
              // Position based on extreme note: for 8va, above highest; for 8vb, below lowest
              // For 8va (TOP): larger line number = higher pitch = more positive offset to push up
              // For 8vb (BOTTOM): smaller line number = lower pitch = more positive offset to push down
              // Bass clef: large positive line = high pitch, small/negative line = low pitch
              const lineOffset = is8va ? (bassHighestPitchLine - 5.0) : (3.5 - bassLowestPitchLine);
              textBracket.setLine(lineOffset);
              textBracket.setContext(context).draw();
            } catch (e) {
              console.warn('Error drawing ottava bracket:', e);
            }
          }
          // Start new bracket
          currentBassOttava = ottavaLabel;
          bassOttavaStart = { measure: i, noteIndex: 0, note: bassNotes[0] };
          bassOttavaEnd = { measure: i, noteIndex: 0, note: bassNotes[0] };
          bassHighestPitchLine = getHighestPitchLine(bassNotes[0]);
          bassLowestPitchLine = getLowestPitchLine(bassNotes[0]);
        }
      } else {
        // No ottava in this measure - draw any pending bracket
        if (currentBassOttava && bassOttavaStart && bassOttavaEnd) {
          try {
            const is8va = currentBassOttava === '8va';
            // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
            const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
            const textBracket = new VF.TextBracket({
              start: bassOttavaStart.note,
              stop: bassOttavaEnd.note,
              text: currentBassOttava,
              superscript: '',
              position: position,
            });
            // For 8va (TOP): larger line number = higher pitch = more positive offset to push up
            // For 8vb (BOTTOM): smaller line number = lower pitch = more positive offset to push down
            const lineOffset = is8va ? (bassHighestPitchLine - 5.0) : (3.5 - bassLowestPitchLine);
            textBracket.setLine(lineOffset);
            textBracket.setContext(context).draw();
          } catch (e) {
            console.warn('Error drawing ottava bracket:', e);
          }
        }
        currentBassOttava = null;
        bassOttavaStart = null;
        bassOttavaEnd = null;
        bassHighestPitchLine = -Infinity;
        bassLowestPitchLine = Infinity;
      }
    }

    // Draw final bracket if exists
    if (currentBassOttava && bassOttavaStart && bassOttavaEnd) {
      try {
        const is8va = currentBassOttava === '8va';
        // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
        const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
        const textBracket = new VF.TextBracket({
          start: bassOttavaStart.note,
          stop: bassOttavaEnd.note,
          text: currentBassOttava,
          superscript: '',
          position: position,
        });
        // For 8va (TOP): larger line number = higher pitch = more positive offset to push up
        // For 8vb (BOTTOM): smaller line number = lower pitch = more positive offset to push down
        const lineOffset = is8va ? (bassHighestPitchLine - 5.0) : (3.5 - bassLowestPitchLine);
        textBracket.setLine(lineOffset);
        textBracket.setContext(context).draw();
      } catch (e) {
        console.warn('Error drawing ottava bracket:', e);
      }
    }

    // Process treble clef brackets with dynamic positioning
    // Note: In treble clef, line numbers work opposite to bass clef:
    // - Small/negative line numbers = high pitch (above staff)
    // - Large positive line numbers = low pitch (below staff)
    let currentTrebleOttava = null;
    let trebleOttavaStart = null;
    let trebleOttavaEnd = null;
    let trebleHighestPitchLine = Infinity; // Track highest pitched note (smallest line number for 8va)
    let trebleLowestPitchLine = -Infinity; // Track lowest pitched note (largest line number for 8vb)

    for (let i = 0; i < renderedMeasures.length; i++) {
      const measure = renderedMeasures[i];
      const trebleNotes = measure.trebleNotes;
      const brackets = measure.trebleOttavaBrackets;

      const hasOttava = brackets && brackets.length > 0;
      const ottavaLabel = hasOttava ? brackets[0].label : null;

      if (ottavaLabel) {
        if (currentTrebleOttava === ottavaLabel) {
          // Continue the bracket
          trebleOttavaEnd = { measure: i, noteIndex: 0, note: trebleNotes[0] };
          // Update extreme note positions
          // For treble clef: smallest line = highest pitch, largest line = lowest pitch
          const highPitchLine = getLowestPitchLine(trebleNotes[0]); // MIN = highest pitch in treble
          const lowPitchLine = getHighestPitchLine(trebleNotes[0]); // MAX = lowest pitch in treble
          if (highPitchLine < trebleHighestPitchLine) trebleHighestPitchLine = highPitchLine;
          if (lowPitchLine > trebleLowestPitchLine) trebleLowestPitchLine = lowPitchLine;
        } else {
          // Draw previous bracket if exists
          if (currentTrebleOttava && trebleOttavaStart && trebleOttavaEnd) {
            try {
              const is8va = currentTrebleOttava === '8va';
              // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
              const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
              const textBracket = new VF.TextBracket({
                start: trebleOttavaStart.note,
                stop: trebleOttavaEnd.note,
                text: currentTrebleOttava,
                superscript: '',
                position: position,
              });
              // For treble clef: smaller line = higher pitch, larger line = lower pitch
              // 8va (TOP): smaller line needs larger positive offset to push bracket higher
              // 8vb (BOTTOM): larger line needs positive offset to push bracket lower
              const lineOffset = is8va ? (8.0 - trebleHighestPitchLine) : (trebleLowestPitchLine - 3.5);
              textBracket.setLine(lineOffset);
              textBracket.setContext(context).draw();
            } catch (e) {
              console.warn('Error drawing ottava bracket:', e);
            }
          }
          // Start new bracket
          currentTrebleOttava = ottavaLabel;
          trebleOttavaStart = { measure: i, noteIndex: 0, note: trebleNotes[0] };
          trebleOttavaEnd = { measure: i, noteIndex: 0, note: trebleNotes[0] };
          trebleHighestPitchLine = getLowestPitchLine(trebleNotes[0]); // MIN = highest pitch in treble
          trebleLowestPitchLine = getHighestPitchLine(trebleNotes[0]); // MAX = lowest pitch in treble
        }
      } else {
        // No ottava in this measure - draw any pending bracket
        if (currentTrebleOttava && trebleOttavaStart && trebleOttavaEnd) {
          try {
            const is8va = currentTrebleOttava === '8va';
            // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
            const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
            const textBracket = new VF.TextBracket({
              start: trebleOttavaStart.note,
              stop: trebleOttavaEnd.note,
              text: currentTrebleOttava,
              superscript: '',
              position: position,
            });
            // For treble clef: smaller line = higher pitch, larger line = lower pitch
            // 8va (TOP): smaller line needs larger positive offset to push bracket higher
            // 8vb (BOTTOM): larger line needs positive offset to push bracket lower
            const lineOffset = is8va ? (8.0 - trebleHighestPitchLine) : (trebleLowestPitchLine - 3.5);
            textBracket.setLine(lineOffset);
            textBracket.setContext(context).draw();
          } catch (e) {
            console.warn('Error drawing ottava bracket:', e);
          }
        }
        currentTrebleOttava = null;
        trebleOttavaStart = null;
        trebleOttavaEnd = null;
        trebleHighestPitchLine = Infinity;
        trebleLowestPitchLine = -Infinity;
      }
    }

    // Draw final treble bracket if exists
    if (currentTrebleOttava && trebleOttavaStart && trebleOttavaEnd) {
      try {
        const is8va = currentTrebleOttava === '8va';
        // Use TOP position for 8va (above notes), BOTTOM position for 8vb (below notes)
        const position = is8va ? TOP_POSITION : BOTTOM_POSITION;
        const textBracket = new VF.TextBracket({
          start: trebleOttavaStart.note,
          stop: trebleOttavaEnd.note,
          text: currentTrebleOttava,
          superscript: '',
          position: position,
        });
        // For treble clef: smaller line = higher pitch, larger line = lower pitch
        // 8va (TOP): smaller line needs larger positive offset to push bracket higher
        // 8vb (BOTTOM): larger line needs positive offset to push bracket lower
        const lineOffset = is8va ? (8.0 - trebleHighestPitchLine) : (trebleLowestPitchLine - 3.5);
        textBracket.setLine(lineOffset);
        textBracket.setContext(context).draw();
      } catch (e) {
        console.warn('Error drawing ottava bracket:', e);
      }
    }
  }

  // NOTE: Experimental chord-duration brackets and labels under the bass staff
  // have been disabled for now. The core staff rendering remains unchanged.

  // TODO: Draw cross-measure ties for bass notes
  // VexFlow 5.x StaveTie API has issues with notes on different staves/pages
  // The `isTied` property is correctly flowing through the data pipeline (see logs above)
  // but VexFlow's tie validation fails for cross-measure ties in multi-page rendering
  //
  // Possible solutions to explore:
  // 1. Use VexFlow's Curve API to manually draw tie curves
  // 2. Render ties within the measure rendering loop instead of after
  // 3. Use a single-page canvas for tie rendering
  //
  // For now, cross-measure ties are visually missing but:
  // ✅ Variable durations work correctly
  // ✅ Playback only triggers once (no retriggering for tied notes)
  // ✅ Chord progression remains stable when changing durations
  // ✅ `isTied` property flows correctly through the entire pipeline

  /* COMMENTED OUT - VexFlow StaveTie fails for cross-measure/cross-page ties
  console.log('[renderGrandStaffSystem] Checking for ties across', renderedMeasures.length, 'measures');
  for (let i = 0; i < renderedMeasures.length - 1; i++) {
    const currentMeasure = renderedMeasures[i];
    const nextMeasure = renderedMeasures[i + 1];

    if (nextMeasure.bassNotes && nextMeasure.bassNotes.length > 0) {
      const firstNextNote = nextMeasure.bassNotes[0];
      if (firstNextNote && firstNextNote.isTied === true) {
        if (currentMeasure.bassNotes && currentMeasure.bassNotes.length > 0) {
          const lastCurrentNote = currentMeasure.bassNotes[currentMeasure.bassNotes.length - 1];
          // Tie drawing code here - currently fails with VexFlow 5.x API
        }
      }
    }
  }
  */

  // Collect all note regions and add chord tone analysis
  const allNoteRegions = [];
  renderedMeasures.forEach((measure) => {
    if (measure.noteRegions) {
      const measureData = measures[measure.index];
      const chord = measureData?.chord;

      measure.noteRegions.forEach((region) => {
        // Add chord tone analysis for tooltip
        let analysis = null;
        if (!region.isRest && chord && chord.root && region.pitch) {
          try {
            analysis = analyzeChordTone(region.pitch, chord, keySignature);
          } catch (e) {
            // Ignore analysis errors
          }
        }

        allNoteRegions.push({
          ...region,
          chord,
          analysis,
        });
      });
    }
  });

  return {
    renderer,
    context,
    dimensions,
    measures: renderedMeasures,
    noteRegions: allNoteRegions,
  };
}

// ============================================================================
// DATA CONVERSION
// ============================================================================

/**
 * Convert existing melody composer data to grand staff format
 * @param {Object} composerData - Existing melody composer data
 * @returns {Array} - Array of grand staff measure data
 */
export function convertToGrandStaffFormat(composerData) {
  const measures = [];
  const {
    melody = [],
    chords = [],
    bassNotes = [],
    timeSignature = '4/4',
    key = 'C',
  } = composerData;

  // Group melody notes by measure
  const notesPerMeasure = getNotesPerMeasure(timeSignature);
  const melodyByMeasure = groupNotesByMeasure(melody, notesPerMeasure);

  // Get number of measures
  const numMeasures = Math.max(
    melodyByMeasure.length,
    chords.length,
    bassNotes.length,
    1
  );

  for (let i = 0; i < numMeasures; i++) {
    const measureData = {
      trebleNotes: [],
      bassNotes: [],
    };

    // Add melody notes to treble
    if (melodyByMeasure[i]) {
      measureData.trebleNotes = melodyByMeasure[i]
        .filter(note => {
          // Keep rests
          if (note.isRest) return true;
          // For non-rests, require valid pitch
          const pitch = note.pitch || note;
          if (pitch && typeof pitch === 'string' && pitch.match(/^[A-G][#b]?\d+$/)) return true;
          // Filter out notes with null/undefined pitch
          return false;
        })
        .map(note => ({
          pitch: note.pitch || note,
          duration: note.duration || '4n',
          isRest: note.isRest || false,
        }));
    }

    // Add bass notes or chord voicing to bass
    if (bassNotes[i]) {
      // If we have explicit bass notes
      if (Array.isArray(bassNotes[i])) {
        measureData.bassNotes = bassNotes[i]
          .filter(note => {
            // Keep rests
            if (note.isRest) return true;
            // For non-rests, require valid pitch
            const pitch = note.pitch || note;
            if (pitch && typeof pitch === 'string' && pitch.match(/^[A-G][#b]?\d+$/)) return true;
            // Filter out notes with null/undefined pitch
            return false;
          })
          .map(note => ({
            pitch: note.pitch || note,
            duration: note.duration || '1n',
            isRest: note.isRest || false,
          }));
      } else {
        // Single bass note - validate before adding
        const pitch = bassNotes[i];
        if (pitch && typeof pitch === 'string' && pitch.match(/^[A-G][#b]?\d+$/)) {
          measureData.bassNotes = [{
            pitch: bassNotes[i],
            duration: '1n',
          }];
        }
      }
    } else if (chords[i]) {
      // Convert chord to bass notes
      const chord = chords[i];
      if (chord.lhNotes && chord.lhNotes.length > 0) {
        measureData.bassNotes = [{
          pitches: chord.lhNotes,
          duration: '1n',
        }];
      } else if (chord.notes && chord.notes.length > 0) {
        // Separate into treble and bass based on octave
        const bassChordNotes = chord.notes.filter(note => {
          const midi = noteToMidi(note);
          return midi < CLEF_RANGES.treble.min;
        });
        if (bassChordNotes.length > 0) {
          measureData.bassNotes = [{
            pitches: bassChordNotes,
            duration: '1n',
          }];
        }
      }
    }

    measures.push(measureData);
  }

  return measures;
}

/**
 * Get number of beats per measure from time signature
 * @param {string} timeSignature - Time signature like "4/4"
 * @returns {number} - Number of beats
 */
function getNotesPerMeasure(timeSignature) {
  const [num, denom] = timeSignature.split('/').map(Number);
  return num;
}

/**
 * Group notes by measure based on their duration
 * @param {Array} notes - Array of notes
 * @param {number} beatsPerMeasure - Beats per measure
 * @returns {Array} - Array of arrays, one per measure
 */
function groupNotesByMeasure(notes, beatsPerMeasure) {
  const measures = [];
  let currentMeasure = [];
  let currentBeat = 0;

  for (const note of notes) {
    const noteDuration = getNoteDurationInBeats(note.duration || '4n');

    if (currentBeat + noteDuration > beatsPerMeasure) {
      // Start new measure
      if (currentMeasure.length > 0) {
        measures.push(currentMeasure);
      }
      currentMeasure = [note];
      currentBeat = noteDuration;
    } else {
      currentMeasure.push(note);
      currentBeat += noteDuration;
    }

    // Check if measure is full
    if (currentBeat >= beatsPerMeasure) {
      measures.push(currentMeasure);
      currentMeasure = [];
      currentBeat = 0;
    }
  }

  // Add remaining notes
  if (currentMeasure.length > 0) {
    measures.push(currentMeasure);
  }

  return measures;
}

/**
 * Get duration in beats
 * @param {string} duration - Tone.js duration
 * @returns {number} - Beats
 */
function getNoteDurationInBeats(duration) {
  const durationMap = {
    '1n': 4,
    '2n': 2,
    '4n': 1,
    '8n': 0.5,
    '16n': 0.25,
    '32n': 0.125,
    '1n.': 6,
    '2n.': 3,
    '4n.': 1.5,
    '8n.': 0.75,
  };
  return durationMap[duration] || 1;
}

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  // Constants
  GRAND_STAFF_DEFAULTS,

  // Dimension calculations
  calculateGrandStaffDimensions,

  // Rendering
  renderGrandStaffMeasure,
  renderGrandStaffSystem,

  // Data conversion
  convertToGrandStaffFormat,
};
