/**
 * Composition State Management Module
 *
 * Unified state for chord progressions and notation composition.
 * Organizes data by measures to enable bi-directional sync between
 * chord progressions and musical notation.
 *
 * Based on Phase 1 of progression-builder-integration.md
 */

import { EventEmitter } from '../utils/eventEmitter.js';
import { generateBassVoicing } from '../integration/bassAutoFill.js';
import { getChordNotes } from '../utils/noteUtils.js';

/**
 * Main composition state class
 * Manages the unified data structure for chord + notation composition
 */
export class CompositionState {
    constructor() {
        // Event emitter for reactivity
        this.events = new EventEmitter();

        // Composition metadata
        this.metadata = {
            title: "",
            composer: "",
            tempo: 120,
            timeSignature: { num: 4, denom: 4 },
            key: "C"
        };

        // Array of measures (each measure contains chord + notation data)
        this.measures = [];

        // Settings for auto-generation behavior
        this.settings = {
            autoGenerateBass: false,       // Auto-fill bass when chord changes (default OFF)
            voiceLeadingStrict: true,      // Use strict voice leading rules
            bassPattern: 'root-fifth',     // Default bass pattern
            highlightChordTones: true,     // Highlight melody notes that are chord tones
            autoHarmonize: false           // Auto-suggest chords from melody
        };

        // Current editing state
        this.cursor = {
            measure: 0,
            beat: 0,
            staff: 'treble',               // 'treble' or 'bass'
            voice: 0                       // Voice index (for polyphony)
        };
    }

    // ========================================================================
    // Measure Management
    // ========================================================================

    /**
     * Add a new measure to the composition
     * @param {object} options - Optional measure configuration
     * @returns {number} Index of the new measure
     */
    addMeasure(options = {}) {
        const measureIndex = this.measures.length;

        const newMeasure = {
            number: measureIndex + 1,

            // Chord data (from Progression Builder)
            chord: options.chord || {
                root: null,
                type: null,
                inversion: 0,
                voicing: "close",
                roman: null,
                name: null,
                notes: []
            },

            // Notation data (for both staves)
            notation: {
                treble: {
                    clef: "treble",
                    voices: [
                        { notes: [] }  // Default single voice
                    ]
                },
                bass: {
                    clef: "bass",
                    voices: [
                        { notes: [] }
                    ],
                    autoGenerated: true  // Track if bass is auto-generated or user-edited
                }
            },

            // Time signature (can change per measure)
            timeSignature: options.timeSignature || this.metadata.timeSignature,

            // Key signature (can change per measure)
            keySignature: options.keySignature || this.metadata.key,

            // Measure-level metadata (for chord symbols, etc.)
            metadata: options.metadata || {}
        };

        this.measures.push(newMeasure);
        this.events.emit('measureAdded', measureIndex, newMeasure);

        return measureIndex;
    }

    /**
     * Remove a measure from the composition
     * @param {number} measureIndex - Index of measure to remove
     */
    removeMeasure(measureIndex) {
        if (measureIndex < 0 || measureIndex >= this.measures.length) {
            console.warn('Invalid measure index:', measureIndex);
            return;
        }

        const removed = this.measures.splice(measureIndex, 1)[0];

        // Renumber remaining measures
        this.measures.forEach((measure, idx) => {
            measure.number = idx + 1;
        });

        this.events.emit('measureRemoved', measureIndex, removed);
    }

    /**
     * Get a specific measure
     * @param {number} measureIndex - Index of measure to get
     * @returns {object|null} Measure object or null if not found
     */
    getMeasure(measureIndex) {
        const measure = this.measures[measureIndex] || null;
        if (measure && !measure.metadata) {
            measure.metadata = {};
        }
        return measure;
    }

    /**
     * Get total number of measures
     * @returns {number} Number of measures
     */
    getMeasureCount() {
        return this.measures.length;
    }

    /**
     * Ensure all measures have metadata property (for backward compatibility)
     * @private
     */
    ensureAllMeasuresHaveMetadata() {
        this.measures.forEach(measure => {
            if (!measure.metadata) {
                measure.metadata = {};
            }
        });
    }

    // ========================================================================
    // Chord Management (Integration with Progression Builder)
    // ========================================================================

    /**
     * Update chord in a specific measure
     * @param {number} measureIndex - Index of measure to update
     * @param {object} chord - Chord data object
     */
    updateChord(measureIndex, chord) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) {
            console.warn('Measure not found:', measureIndex);
            return;
        }

        const previousChord = { ...measure.chord };
        measure.chord = { ...measure.chord, ...chord };

        this.events.emit('chordChanged', measureIndex, measure.chord, previousChord);

        // Auto-update bass if enabled
        if (this.settings.autoGenerateBass && measure.notation.bass.autoGenerated) {
            this.updateBassFromChord(measureIndex);
        }
    }

    /**
     * Get chord from a specific measure
     * @param {number} measureIndex - Index of measure
     * @returns {object|null} Chord object or null if not found
     */
    getChord(measureIndex) {
        const measure = this.getMeasure(measureIndex);
        return measure ? measure.chord : null;
    }

    /**
     * Auto-generate bass voicing from chord
     * @param {number} measureIndex - Index of measure to update
     */
    updateBassFromChord(measureIndex) {
        const measure = this.getMeasure(measureIndex);
        if (!measure || !measure.chord.root) return;

        const chord = measure.chord;
        const previousMeasure = this.getMeasure(measureIndex - 1);
        const previousChord = previousMeasure ? previousMeasure.chord : null;

        // Determine how many beats this chord occupies in this measure
        const beatsInMeasure = chord.beatsInMeasure || 4;
        const isChordContinuation = chord.isChordContinuation || false;

        // Generate bass voicing using the bassAutoFill module
        const bassVoicing = generateBassVoicing(chord, previousChord, {
            voiceLeadingStrict: this.settings.voiceLeadingStrict,
            bassPattern: this.settings.bassPattern,
            timeSignature: measure.timeSignature || this.metadata.timeSignature,
            beatsInMeasure: beatsInMeasure, // Pass the beats for this measure
            isChordContinuation: isChordContinuation // Indicate if this is a tied continuation
        });

        // Update bass clef notes
        measure.notation.bass.voices[0].notes = bassVoicing.notes;
        measure.notation.bass.autoGenerated = true;

        // CRITICAL: Store the generated bass notes in the chord object
        // so the NEXT chord can use them for voice leading
        measure.chord.bass = {
            notes: bassVoicing.notes
        };

        this.events.emit('bassUpdated', measureIndex, bassVoicing);
    }

    // ========================================================================
    // Notation Management (Melody and Bass Editing)
    // ========================================================================

    /**
     * Add note to a specific staff and voice
     * @param {number} measureIndex - Index of measure
     * @param {string} staff - 'treble' or 'bass'
     * @param {number} voiceIndex - Voice index (0-based)
     * @param {object} note - Note object
     */
    addNote(measureIndex, staff, voiceIndex, note) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) {
            console.warn('Measure not found:', measureIndex);
            return;
        }

        const staffData = measure.notation[staff];
        if (!staffData) {
            console.warn('Invalid staff:', staff);
            return;
        }

        // Ensure voice exists
        while (staffData.voices.length <= voiceIndex) {
            staffData.voices.push({ notes: [] });
        }

        staffData.voices[voiceIndex].notes.push(note);

        // If editing bass manually, mark it as not auto-generated
        if (staff === 'bass') {
            measure.notation.bass.autoGenerated = false;
        }

        this.events.emit('noteAdded', measureIndex, staff, voiceIndex, note);
    }

    /**
     * Update a specific note
     * @param {number} measureIndex - Index of measure
     * @param {string} staff - 'treble' or 'bass'
     * @param {number} voiceIndex - Voice index
     * @param {number} noteIndex - Note index within voice
     * @param {object} changes - Properties to update
     */
    updateNote(measureIndex, staff, voiceIndex, noteIndex, changes) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return;

        const voice = measure.notation[staff].voices[voiceIndex];
        if (!voice || !voice.notes[noteIndex]) return;

        const oldNote = { ...voice.notes[noteIndex] };
        voice.notes[noteIndex] = { ...voice.notes[noteIndex], ...changes };

        this.events.emit('noteUpdated', measureIndex, staff, voiceIndex, noteIndex, oldNote);
    }

    /**
     * Remove a note
     * @param {number} measureIndex - Index of measure
     * @param {string} staff - 'treble' or 'bass'
     * @param {number} voiceIndex - Voice index
     * @param {number} noteIndex - Note index to remove
     */
    removeNote(measureIndex, staff, voiceIndex, noteIndex) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return;

        const voice = measure.notation[staff].voices[voiceIndex];
        if (!voice) return;

        const removed = voice.notes.splice(noteIndex, 1)[0];

        // If editing bass manually, mark it as not auto-generated
        if (staff === 'bass') {
            measure.notation.bass.autoGenerated = false;
        }

        this.events.emit('noteRemoved', measureIndex, staff, voiceIndex, noteIndex, removed);
    }

    /**
     * Get all notes from a specific staff/voice in a measure
     * @param {number} measureIndex - Index of measure
     * @param {string} staff - 'treble' or 'bass'
     * @param {number} voiceIndex - Voice index
     * @returns {array} Array of note objects
     */
    getNotes(measureIndex, staff, voiceIndex = 0) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return [];

        const voice = measure.notation[staff].voices[voiceIndex];
        return voice ? voice.notes : [];
    }

    // ========================================================================
    // Import/Export - Integration with existing systems
    // ========================================================================

    /**
     * Import from existing progressionData array (from trainerState)
     * @param {array} progressionData - Array of chord objects
     * @param {object} options - Import options
     */
    importFromProgressionData(progressionData, options = {}) {
        // Clear existing measures
        this.measures = [];

        // Update metadata
        if (options.key) this.metadata.key = options.key;
        if (options.tempo) this.metadata.tempo = options.tempo;
        if (options.timeSignature) this.metadata.timeSignature = options.timeSignature;

        // Get time signature to determine beats per measure
        const timeSignature = this.metadata.timeSignature || { num: 4, denom: 4 };
        const beatsPerMeasure = timeSignature.num || timeSignature.numerator || 4;

        // Process each chord, potentially splitting across multiple measures
        progressionData.forEach((chordData, chordIndex) => {
            const chordBeats = chordData.beats !== undefined ? chordData.beats : 4;
            let remainingBeats = chordBeats;
            let measureStartBeat = 0;

            // Split chord across measures if it spans more than one measure
            while (remainingBeats > 0) {
                const beatsInThisMeasure = Math.min(remainingBeats, beatsPerMeasure - measureStartBeat);

                const measureIndex = this.addMeasure({
                    chord: {
                        root: chordData.root,
                        type: chordData.type,
                        inversion: chordData.inversion || 0,
                        voicing: "close",
                        roman: chordData.roman,
                        name: chordData.name || chordData.simpleName,
                        notes: chordData.notes || [],
                        beats: chordBeats, // Store total beats for the chord
                        beatsInMeasure: beatsInThisMeasure, // Beats used in this specific measure
                        chordIndex: chordIndex, // Track which chord this belongs to
                        isChordContinuation: measureStartBeat > 0 || remainingBeats !== chordBeats // Is this a continuation?
                    }
                });

                // Auto-generate bass if enabled
                if (this.settings.autoGenerateBass) {
                    this.updateBassFromChord(measureIndex);
                }

                remainingBeats -= beatsInThisMeasure;
                measureStartBeat = (measureStartBeat + beatsInThisMeasure) % beatsPerMeasure;
            }
        });

        this.events.emit('progressionImported', progressionData);
    }

    /**
     * Sync with progressionData (preserving melody)
     * Updates chords and structure to match progressionData, but keeps existing melody notes.
     * @param {array} progressionData - Array of chord objects
     * @param {object} options - Sync options
     */
    syncWithProgressionData(progressionData, options = {}) {
        // Update metadata if provided
        if (options.key) this.metadata.key = options.key;
        if (options.tempo) this.metadata.tempo = options.tempo;
        if (options.timeSignature) this.metadata.timeSignature = options.timeSignature;

        // Get time signature to determine beats per measure
        const timeSignature = this.metadata.timeSignature || { num: 4, denom: 4 };
        const beatsPerMeasure = timeSignature.num || timeSignature.numerator || 4;

        // Calculate how many measures we need based on chord durations
        let requiredMeasures = 0;
        let currentBeat = 0;

        console.log(`[syncWithProgressionData] beatsPerMeasure: ${beatsPerMeasure}, timeSignature:`, timeSignature);

        progressionData.forEach((chordData, idx) => {
            const chordBeats = chordData.beats !== undefined ? chordData.beats : 4;
            console.log(`[syncWithProgressionData] Chord ${idx}: beats=${chordBeats}, chord.beats=${chordData.beats}, chordData:`, chordData);
            currentBeat += chordBeats;
            requiredMeasures = Math.ceil(currentBeat / beatsPerMeasure);
        });

        console.log(`[syncWithProgressionData] Processing ${progressionData.length} chords, will create ${requiredMeasures} measures, currentBeat=${currentBeat}`);

        // Store existing melody notes before restructuring
        const melodyBackup = this.measures.map((measure, idx) => ({
            index: idx,
            notes: measure.notation.treble.voices[0].notes || []
        }));

        // Clear measures and rebuild with new structure
        this.measures = [];

        // Process each chord, potentially splitting across multiple measures
        let currentMeasureIndex = -1; // Will increment to 0 on first measure creation
        let currentBeatInMeasure = 0; // Track which beat we're at in the current measure

        progressionData.forEach((chordData, chordIndex) => {
            const chordBeats = chordData.beats !== undefined ? chordData.beats : 4;
            let remainingBeats = chordBeats;
            let isFirstSegmentOfChord = true;

            // Get chord notes
            let notes = chordData.notes || [];
            if (notes.length === 0 && chordData.root && chordData.type) {
                const chordNotesObj = getChordNotes(chordData.root, chordData.type, this.metadata.key);
                if (chordNotesObj && chordNotesObj.specificNotes) {
                    notes = chordNotesObj.specificNotes;
                }
            }

            // Split chord across measures if necessary
            while (remainingBeats > 0) {
                // Create new measure if we need one (either first measure or current is full)
                if (currentBeatInMeasure === 0) {
                    currentMeasureIndex++;
                    this.addMeasure({
                        chord: {
                            root: chordData.root,
                            type: chordData.type,
                            inversion: chordData.inversion || 0,
                            voicing: "close",
                            roman: chordData.roman,
                            name: chordData.name || chordData.simpleName,
                            notes: notes,
                            beats: chordBeats,
                            beatsInMeasure: 0, // Will calculate this as we add notes
                            chordIndex: chordIndex,
                            isChordContinuation: false
                        }
                    });
                    console.log(`[syncWithProgressionData] Created measure ${currentMeasureIndex}`);
                }

                const beatsInThisMeasure = Math.min(remainingBeats, beatsPerMeasure - currentBeatInMeasure);
                const measure = this.getMeasure(currentMeasureIndex);

                if (measure && notes.length > 0) {
                    // Determine the appropriate duration for this chord segment
                    const duration = beatsInThisMeasure === 4 ? '1n' :
                                   beatsInThisMeasure === 2 ? '2n' :
                                   beatsInThisMeasure === 1 ? '4n' :
                                   beatsInThisMeasure === 3 ? '2n.' :
                                   beatsInThisMeasure === 1.5 ? '4n.' :
                                   beatsInThisMeasure === 0.5 ? '8n' :
                                   '1n'; // fallback

                    const chordNote = {
                        type: 'note',
                        pitches: [...notes],
                        duration: duration,
                        beat: currentBeatInMeasure,
                        dotted: duration.includes('.'),
                        isTied: !isFirstSegmentOfChord // Tied if not the first segment
                    };

                    // Add this note to the bass clef
                    measure.notation.bass.voices[0].notes.push(chordNote);
                    measure.notation.bass.autoGenerated = false;

                    console.log(`[syncWithProgressionData]   → Added bass note to measure ${currentMeasureIndex}: chord=${chordIndex}, duration=${duration}, beat=${currentBeatInMeasure}, tied=${chordNote.isTied}, pitches=${notes.length}`);
                }

                remainingBeats -= beatsInThisMeasure;
                currentBeatInMeasure += beatsInThisMeasure;
                isFirstSegmentOfChord = false;

                // If we've filled the measure, reset for next measure
                if (currentBeatInMeasure >= beatsPerMeasure) {
                    currentBeatInMeasure = 0;
                }
            }
        });

        // Restore melody notes where possible
        melodyBackup.forEach(backup => {
            if (backup.index < this.measures.length && backup.notes.length > 0) {
                this.measures[backup.index].notation.treble.voices[0].notes = backup.notes;
            }
        });

        this.events.emit('progressionSynced', progressionData);
    }

    /**
     * Export to progressionData format (for compatibility with existing code)
     * IMPORTANT: Only exports unique chords (not measure continuations from splitting)
     * @returns {array} Array of chord objects
     */
    exportToProgressionData() {
        const uniqueChords = [];
        const seenChordIndices = new Set();

        this.measures.forEach(measure => {
            const chordIndex = measure.chord.chordIndex;

            // Only export the first measure for each chord (skip continuations)
            if (chordIndex !== undefined && !seenChordIndices.has(chordIndex)) {
                seenChordIndices.add(chordIndex);

                uniqueChords.push({
                    root: measure.chord.root,
                    type: measure.chord.type,
                    inversion: measure.chord.inversion,
                    roman: measure.chord.roman,
                    name: measure.chord.name,
                    notes: measure.chord.notes,
                    beats: measure.chord.beats, // Include the original beats value
                    selectionMode: 'chord',
                    omittedNotes: measure.chord.omittedNotes || [],
                    lhOmittedNotes: measure.chord.lhOmittedNotes || [],
                    octaveShift: measure.chord.octaveShift || 0,
                    lhOctaveShift: measure.chord.lhOctaveShift || 0,
                    lhType: measure.chord.lhType || 'auto',
                    lhInversion: measure.chord.lhInversion || 0
                });
            }
        });

        console.log(`[exportToProgressionData] Exported ${uniqueChords.length} unique chords from ${this.measures.length} measures`);
        console.log('[exportToProgressionData] Stack trace:', new Error().stack);
        return uniqueChords;
    }

    /**
     * Import from interactiveMelody format (from melodyGenerator.js)
     * @param {object} interactiveMelody - Melody object
     */
    importFromInteractiveMelody(interactiveMelody) {
        // Update metadata
        this.metadata.tempo = interactiveMelody.tempo || 120;
        this.metadata.key = interactiveMelody.key || 'C';

        const [num, denom] = interactiveMelody.timeSignature.split('/').map(Number);
        this.metadata.timeSignature = { num, denom };

        // Group notes by measure
        const notesByMeasure = new Map();

        // Process melody notes (treble staff)
        interactiveMelody.melodyNotes.forEach(note => {
            if (!notesByMeasure.has(note.measure)) {
                notesByMeasure.set(note.measure, { treble: [], bass: [] });
            }
            notesByMeasure.get(note.measure).treble.push(note);
        });

        // Process chord notes (currently visualization, will become bass)
        if (interactiveMelody.chordNotes) {
            interactiveMelody.chordNotes.forEach(note => {
                if (!notesByMeasure.has(note.measure)) {
                    notesByMeasure.set(note.measure, { treble: [], bass: [] });
                }
                notesByMeasure.get(note.measure).bass.push(note);
            });
        }

        // Create measures
        const maxMeasure = Math.max(...notesByMeasure.keys(), 0);
        for (let i = 0; i <= maxMeasure; i++) {
            const notes = notesByMeasure.get(i) || { treble: [], bass: [] };

            const measureIndex = this.addMeasure({});
            const measure = this.getMeasure(measureIndex);

            // Add treble notes
            measure.notation.treble.voices[0].notes = notes.treble;

            // Add bass notes (if any)
            if (notes.bass.length > 0) {
                measure.notation.bass.voices[0].notes = notes.bass;
                measure.notation.bass.autoGenerated = false; // User had notes here
            }
        }

        this.events.emit('melodyImported', interactiveMelody);
    }

    /**
     * Export to interactiveMelody format (for compatibility)
     * @returns {object} Interactive melody object
     */
    exportToInteractiveMelody() {
        const melodyNotes = [];
        const chordNotes = [];

        this.measures.forEach((measure, measureIndex) => {
            // Export treble notes
            measure.notation.treble.voices.forEach(voice => {
                voice.notes.forEach(note => {
                    melodyNotes.push({ ...note, measure: measureIndex });
                });
            });

            // Export bass notes
            measure.notation.bass.voices.forEach(voice => {
                voice.notes.forEach(note => {
                    chordNotes.push({ ...note, measure: measureIndex });
                });
            });
        });

        return {
            melodyNotes,
            chordNotes,
            timeSignature: `${this.metadata.timeSignature.num}/${this.metadata.timeSignature.denom}`,
            beatsPerMeasure: this.metadata.timeSignature.num,
            beatDuration: this.metadata.timeSignature.denom === 4 ? '4n' : '8n',
            tempo: this.metadata.tempo,
            key: this.metadata.key
        };
    }

    // ========================================================================
    // Settings Management
    // ========================================================================

    /**
     * Update composition settings
     * @param {object} settings - Settings to update
     */
    updateSettings(settings) {
        this.settings = { ...this.settings, ...settings };
        this.events.emit('settingsUpdated', this.settings);
    }

    /**
     * Get current settings
     * @returns {object} Settings object
     */
    getSettings() {
        return { ...this.settings };
    }

    // ========================================================================
    // Utility Methods
    // ========================================================================

    /**
     * Clear all composition data
     */
    clear() {
        this.measures = [];
        this.cursor = { measure: 0, beat: 0, staff: 'treble', voice: 0 };
        this.events.emit('cleared');
    }

    /**
     * Get full composition data as JSON
     * @returns {object} Complete composition data
     */
    toJSON() {
        return {
            metadata: { ...this.metadata },
            measures: this.measures.map(m => ({ ...m })),
            settings: { ...this.settings }
        };
    }

    /**
     * Load composition from JSON
     * @param {object} data - Composition data
     */
    fromJSON(data) {
        if (data.metadata) this.metadata = { ...data.metadata };
        if (data.measures) {
            this.measures = data.measures.map(m => ({
                ...m,
                // Ensure metadata exists for all measures (for chord symbols, etc.)
                metadata: m.metadata || {}
            }));
        }
        if (data.settings) this.settings = { ...data.settings };

        this.events.emit('loaded', data);
    }

    // ========================================================================
    // Helper Methods for Playback (replaces legacy interactiveMelody.melodyNotes)
    // ========================================================================

    /**
     * Get all melody notes across all measures
     * @returns {Array} All treble clef notes with measure and beat info
     */
    getAllMelodyNotes() {
        const allNotes = [];
        this.measures.forEach((measure, measureIndex) => {
            const trebleNotes = measure.notation.treble.voices[0].notes || [];
            trebleNotes.forEach((note, noteIndex) => {
                allNotes.push({
                    ...note,
                    measure: measureIndex,
                    noteIndex: noteIndex,
                    beat: note.beat || 0
                });
            });
        });
        return allNotes;
    }

    /**
     * Get all bass notes across all measures
     * @returns {Array} All bass clef notes with measure and beat info
     */
    getAllBassNotes() {
        const allNotes = [];
        this.measures.forEach((measure, measureIndex) => {
            const bassNotes = measure.notation.bass.voices[0].notes || [];
            bassNotes.forEach((note, noteIndex) => {
                allNotes.push({
                    ...note,
                    measure: measureIndex,
                    noteIndex: noteIndex,
                    beat: note.beat || 0
                });
            });
        });
        return allNotes;
    }

    /**
     * Get melody notes in a specific measure
     * @param {number} measureIndex - Measure index
     * @returns {Array} Notes in the measure
     */
    getMelodyNotesInMeasure(measureIndex) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return [];
        return measure.notation.treble.voices[0].notes || [];
    }

    /**
     * Get bass notes in a specific measure
     * @param {number} measureIndex - Measure index
     * @returns {Array} Notes in the measure
     */
    getBassNotesInMeasure(measureIndex) {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return [];
        return measure.notation.bass.voices[0].notes || [];
    }

    /**
     * Get notes on a specific beat within a measure
     * @param {number} measureIndex - Measure index
     * @param {number} beat - Beat number
     * @param {string} staff - 'treble' or 'bass' (default: 'treble')
     * @returns {Array} Notes on that beat
     */
    getNotesByBeat(measureIndex, beat, staff = 'treble') {
        const measure = this.getMeasure(measureIndex);
        if (!measure) return [];

        const voiceKey = staff === 'treble' ? 'treble' : 'bass';
        const notes = measure.notation[voiceKey].voices[0].notes || [];

        return notes.filter(note => {
            const noteBeat = note.beat || 0;
            return Math.abs(noteBeat - beat) < 0.001; // Float comparison tolerance
        });
    }

    /**
     * Search backward for the last effective dynamic marking
     * Used for dynamic inheritance (pp, p, mp, mf, f, ff, etc.)
     * @param {number} measureIndex - Current measure index
     * @param {number} noteIndexInMeasure - Current note index within measure
     * @param {string} staff - 'treble' or 'bass' (default: 'treble')
     * @returns {string|null} Last dynamic marking or null
     */
    getEffectiveDynamicUpTo(measureIndex, noteIndexInMeasure, staff = 'treble') {
        // Search backward in current measure
        const measure = this.getMeasure(measureIndex);
        if (measure) {
            const voiceKey = staff === 'treble' ? 'treble' : 'bass';
            const notes = measure.notation[voiceKey].voices[0].notes || [];

            for (let i = noteIndexInMeasure; i >= 0; i--) {
                if (notes[i]?.dynamic) {
                    return notes[i].dynamic;
                }
            }
        }

        // Search backward through previous measures
        for (let m = measureIndex - 1; m >= 0; m--) {
            const prevMeasure = this.getMeasure(m);
            if (prevMeasure) {
                const voiceKey = staff === 'treble' ? 'treble' : 'bass';
                const notes = prevMeasure.notation[voiceKey].voices[0].notes || [];

                for (let i = notes.length - 1; i >= 0; i--) {
                    if (notes[i]?.dynamic) {
                        return notes[i].dynamic;
                    }
                }
            }
        }

        return null;
    }

    /**
     * Check if composition has any melody notes
     * @returns {boolean} True if there are any treble notes
     */
    hasMelodyNotes() {
        return this.getAllMelodyNotes().length > 0;
    }

    /**
     * Check if composition has any bass notes
     * @returns {boolean} True if there are any bass notes
     */
    hasBassNotes() {
        return this.getAllBassNotes().length > 0;
    }

    /**
     * Get the last note in the composition (for "delete last note" functionality)
     * @param {string} staff - 'treble' or 'bass' (default: 'treble')
     * @returns {Object|null} Last note with measure/noteIndex info, or null
     */
    getLastNote(staff = 'treble') {
        const allNotes = staff === 'treble' ? this.getAllMelodyNotes() : this.getAllBassNotes();
        return allNotes.length > 0 ? allNotes[allNotes.length - 1] : null;
    }

    /**
     * Delete the last note in the composition
     * @param {string} staff - 'treble' or 'bass' (default: 'treble')
     * @returns {Object|null} The deleted note, or null if no notes exist
     */
    deleteLastNote(staff = 'treble') {
        const lastNote = this.getLastNote(staff);
        if (!lastNote) return null;

        const measure = this.getMeasure(lastNote.measure);
        if (measure) {
            const voiceKey = staff === 'treble' ? 'treble' : 'bass';
            const notes = measure.notation[voiceKey].voices[0].notes;
            const deleted = notes.splice(lastNote.noteIndex, 1)[0];
            this.events.emit('noteDeleted', { measureIndex: lastNote.measure, staff, noteIndex: lastNote.noteIndex });
            return deleted;
        }

        return null;
    }
}

// ============================================================================
// Singleton Instance (for backward compatibility)
// ============================================================================

let compositionStateInstance = null;

/**
 * Get or create the global composition state instance
 * @returns {CompositionState} Composition state instance
 */
export function getCompositionState() {
    if (!compositionStateInstance) {
        compositionStateInstance = new CompositionState();
    }
    return compositionStateInstance;
}

/**
 * Reset the global composition state instance
 */
export function resetCompositionState() {
    compositionStateInstance = new CompositionState();
    return compositionStateInstance;
}
